### ISSUE TITLE
Not work for the latest Typora version (1.9.4) on MacOS

### ISSUE THREAD

**Issue by HenryZhou19** [Snowflyt/typora-copilot#11]
I successfully installed Typora-Copilot by the recommended way. And Node20 is available. But I can not find anything different before and after the installation.
<img width="977" alt="Snipaste_2024-08-01_16-05-58" src="https://github.com/user-attachments/assets/b0b20d9c-cc83-4e17-b1aa-051a6f0c7c42">
<img width="148" alt="Snipaste_2024-08-01_16-06-29" src="https://github.com/user-attachments/assets/7357297b-6b60-4a18-85f2-a0ca25d3311d">
<img width="1680" alt="Snipaste_2024-08-01_16-07-22" src="https://github.com/user-attachments/assets/d235ac33-37f5-4191-92d3-a1fc4e74e6b1">

**Comment by HenryZhou19** [comment]
> I successfully installed Typora-Copilot by the recommended way. And Node20 is available. But I can not find anything different before and after the installation. <img alt="Snipaste_2024-08-01_16-05-58" width="977" src="https://private-user-images.githubusercontent.com/92938522/354140658-b0b20d9c-cc83-4e17-b1aa-051a6f0c7c42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDA4MjUsIm5iZiI6MTcyMjUwMDUyNSwicGF0aCI6Ii85MjkzODUyMi8zNTQxNDA2NTgtYjBiMjBkOWMtY2M4My00ZTE3LWIxYWEtMDUxYTZmMGM3YzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA4MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExODVjNWI1MTA3NjkxODE3ZmU4ZTIxZDI2MWM5ODZkZDk4MDA3ZWI2NGY4MTJiOWM2ZTVlMDc1YTQyN2ViYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EjrPwm6cV4YNnLyFAtVwBz-M1oaqWNcmQN1SEiyahHI"> <img alt="Snipaste_2024-08-01_16-06-29" width="148" src="https://private-user-images.githubusercontent.com/92938522/354140688-7357297b-6b60-4a18-85f2-a0ca25d3311d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDA4MjUsIm5iZiI6MTcyMjUwMDUyNSwicGF0aCI6Ii85MjkzODUyMi8zNTQxNDA2ODgtNzM1NzI5N2ItNmI2MC00YTE4LTg1ZjItYTBjYTI1ZDMzMTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA4MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMGVhN2M3ZjlmYTJjZjc3N2Y4NGY1NTNlOTk3OWI4NTFkMTY2NGQzZWMxMWMwMTM2ZDA5ZTg3YmMwZTFmZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.js15NK3acjRff-QoB_WRTZAZy4OD6UV6STpBaHaL0MM"> <img alt="Snipaste_2024-08-01_16-07-22" width="1680" src="https://private-user-images.githubusercontent.com/92938522/354140696-d235ac33-37f5-4191-92d3-a1fc4e74e6b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDA4MjUsIm5iZiI6MTcyMjUwMDUyNSwicGF0aCI6Ii85MjkzODUyMi8zNTQxNDA2OTYtZDIzNWFjMzMtMzdmNS00MTkxLTkyZDMtYTFmYzRlNzRlNmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA4MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MDE0ZmM3ZmE2ZDNjMzdjZDhiNTdhNjRhYzBkODU5NjFlNGNhZDQ4NjlhOGFiN2QwYTY5ZTgwYTI4MTQ0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E3a8jUGMYmyT1GNDjGTOZOyojw5AldIwO_ffI-dEh5o">

For more information, there's another try. I installed the 1.8.10 Typora after uninstalling the latest one completely, but this time I failed in the installation of Typora-Copilot.
<img width="720" alt="Snipaste_2024-08-01_16-21-55" src="https://github.com/user-attachments/assets/bb501ab9-eddd-4e00-9514-7c24fe5928fe">

**Comment by Snowflyt** [comment]
Node.js is not really required for just “installing” the plugin — the plugin itself will find if Node.js is available on startup and prompt you to install Node.js if it is not found. Seems the only possible reason is that you failed to install the plugin itself.

Consider uninstalling Typora completely and then install this plugin. It should take effect after you restarted Typora.

The plugin works pretty well on my Macbook Pro M2 for Typora 1.9.4, the `README.md` is just not updated since the last release.

**Comment by Snowflyt** [comment]
Also, make sure your network can connect to GitHub Copilot.

**Comment by HenryZhou19** [comment]
So how can I completely uninstall Typora on MacOS?
I just moved it to the trash bin, and my cleaning tool app helped me to delete some relevant files. Are these steps effective?

**Comment by Snowflyt** [comment]
> So how can I completely uninstall Typora on MacOS? I just moved it to the trash bin, and my cleaning tool app helped me to delete some relevant files. Are these steps effective?

That seems enough. Still unable to use the plugin after reinstallation?

**Comment by HenryZhou19** [comment]
Still failed. And no message in the debugging console ("502 bad gateway" shown at the bottom).
Using the same network, Typora works well with the plugin on my Windows PC.
I'll try more if I have free time in the next few days.

**Comment by Snowflyt** [comment]
> I've found some things interesting: If I open Typora from the Dashboard Icon or the Typora.app in Applications folder, the plugin will never start working. But if I open it from /Applications/Typora.app/Contents/MacOS/Typora, then the copilot will show at the right bottom corner of the Typora window.

Sounds strange. That never happened on my device. I think this might stem from some security mechanisms in macOS, or possibly uninstalling remnants. Perhaps I've never encountered this issue because I've always used AppCleaner to uninstall software.

I’ll consider adding this to README in the next version.

**Comment by HenryZhou19** [comment]
I've tried AppCleaner with all possible checkboxes checked when uninstalling Typora, and rebooted my Mac before reinstall it. The problem remains.
Thanks much for your time. I'll just use it by the special launch method. Hope this could be solved someday.
