### ISSUE TITLE
typora copilot:dialog.warn-nodejs-required-for-typora-under-1-6.title

### ISSUE THREAD

**Issue by LEONliaowin** [Snowflyt/typora-copilot#12]
typora copilot:dialog.warn-nodejs-required-for-typora-under-1-6.title
怎么解决

**Comment by Snowflyt** [comment]
字面意思，如果你使用 Typora < 1.6 需要安装 Node.js 才能运行。

另外你好歹给个截图吧，这我也看不出更多信息
