### ISSUE TITLE
mydockfinder截图工具失灵

### ISSUE THREAD

**Issue by LEONliaowin** [Snowflyt/typora-copilot#13]
Windows使用了mydockfinder之后截图工具打不开，有无大神知道如何解决

**Comment by Snowflyt** [comment]
没用过这个软件。按理来说 Typora Copilot 只是个插件，安装它本身不会造成任何其他影响。安装过程本身也就是把插件下载到指定文件夹然后改一下 Typora 源码。

我不认为安装插件本身会造成与其他软件的兼容性问题，有更多信息可以提供吗？你是怎么安装的插件？

**Comment by Snowflyt** [comment]
长时间未收到回应，无法复现，关闭该 Issue

希望以后不要再出现这种前因后果说不清楚的 Issue，谢谢
