### ISSUE TITLE
Typora Copilot: Node.js is required on macOS, Node.js >= 18 is required to run this plugin.

### ISSUE THREAD

**Issue by erich2s** [Snowflyt/typora-copilot#6]
## 运行环境：
- 芯片：M1 pro
- 系统：macOS 14.4.1
- Node Version：v20.12.0, v18.12.0(使用nvm管理，来回切换这两个版本也都不行😭)
- Typora Version：v1.8.10

**Comment by Snowflyt** [comment]
你 NVM 的初始化脚本放 ~/.zshrc 里了没？

**Comment by Snowflyt** [comment]
或者你试试用 brew 管理 Node，在我的电脑上用 Homebrew 是可以的😂Homebrew 倒也能在多个 Node 版本之间切换，我还写过篇[教程](https://zhuanlan.zhihu.com/p/676944997)呢

**Comment by Snowflyt** [comment]
需要确保你正常在 Shell 环境里能访问 `node` 命令，在 bashrc 和 zshrc 里都放一下试试

**Comment by erich2s** [comment]
我的nvm是通过homebrew安装的，.zshrc也确实加载了nvm的初始化脚本，但是就是失败。我把node的路径切换成homebrew安装的后就可以了，可能是nvm的问题吧。。
![CleanShot 2024-03-30 at 18 42 15@2x](https://github.com/Snowflyt/typora-copilot/assets/53571741/333de0a9-4350-45cf-a349-c8c552cda81b)

**Comment by Snowflyt** [comment]
Typora 这边默认调用的应该是 Bash，感觉是 Bash 的问题。你试试把 NVM 初始化脚本放到 ~/.bashrc 里边，我刚才试了下应该是这个问题

**Comment by Snowflyt** [comment]
Homebrew 安装的 Node 链接到 /opt/homebrew/bin/node 下，而 /opt/homebrew/bin 在 PATH 里边，所以能够探测到

**Comment by erich2s** [comment]
nvm初始化脚本加进了bashrc里还是不行，难搞

**Comment by Snowflyt** [comment]
我下个版本看看做个允许使用自定义路径 Node 的功能吧😂

**Comment by erich2s** [comment]
感谢，已正常工作！
