### ISSUE TITLE
completion deactivation

### ISSUE THREAD

**Issue by TartexFumex** [Snowflyt/typora-copilot#7]
Hello,
Thank you for your work and your useful plugin, it helps me a lot.
However, is it possible to add the completion deactivation feature like in Visual Studio? I sometimes have problems when I use the plugin with the code block(mermaid, python,...), and also with the ``$$`` block.
Thanks
TartexFumex

**Comment by Snowflyt** [comment]
This is a great idea and should be relatively easy to implement. I think I'll include it in the next release.

**Comment by TartexFumex** [comment]
ok thank you

**Comment by Snowflyt** [comment]
Fixed in 9cfabe94fc3e7b6b614eb7c198c86d66065a741a.

It is already included in the newest v0.3.0 version.
