### ISSUE TITLE
Can not find the "Disable completions" button.

### ISSUE THREAD

**Issue by HenryZhou19** [Snowflyt/typora-copilot#8]
Thank you very much for your work!

I want to disable the Copilot manually, but I can not find the "Disable completions" button as README says.
Please help me with it.
![Snipaste_2024-07-15_11-01-23](https://github.com/user-attachments/assets/bb5c0c7a-071b-4f17-a9ce-189a948d8f4e)

**Comment by Snowflyt** [comment]
Have you installed the latest version of Typora Copilot? If so, you should have seen more options than just "Sign out".

Try to uninstall Typora completely and remove the folder `C:\Program Files\Typora` manually (or similar ones if you're using macOS or Linux). Then install Typora and this plugin again.

By the way, what's your OS? Windows, macOS or any Linux distribution?

**Comment by HenryZhou19** [comment]
It really works!
I completely reinstalled Typora and the latest plugin. Three buttons are available for me now.
BTW, I'm using Windows 10.
Thanks again~
